

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCFService.DataAccessLayer
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Data.Entity.Infrastructure;

    public class DataquadEntities : DbContext
    {
        public DataquadEntities(DbContextOptions<DataquadEntities> options)
         : base(options)
        {

        }

        public virtual DbSet<tbl_race> tbl_race { get; set; }

        public virtual DbSet<tbl_userDetails> tbl_userDetails { get; set; }

        public virtual DbSet<tbl_userFilesCollection> tbl_userFilesCollection { get; set; }

        public virtual DbSet<tbl_userLoginDetails> tbl_userLoginDetails { get; set; }

        public virtual DbSet<tbl_userPersonalDetail> tbl_userPersonalDetail { get; set; }

        public virtual DbSet<tbl_userProfileImages> tbl_userProfileImages { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbl_race>().ToTable("tbl_race");
            modelBuilder.Entity<tbl_userDetails>().ToTable("tbl_userDetails");
            modelBuilder.Entity<tbl_userFilesCollection>().ToTable("tbl_userFilesCollection");
            modelBuilder.Entity<tbl_userLoginDetails>().ToTable("tbl_userLoginDetails");
            modelBuilder.Entity<tbl_userPersonalDetail>().ToTable("tbl_userPersonalDetail");
            modelBuilder.Entity<tbl_userProfileImages>().ToTable("tbl_userProfileImages");
        }
    }
}

