
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace WCFService.DataAccessLayer
{

    public class tbl_race
    {
        public int raceId { get; set; }

        public string raceName { get; set; }
    }

}
