
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace WCFService.DataAccessLayer
{
    public partial class tbl_userDetails
    {
        //public tbl_userDetails()
        //{
        //    this.tbl_userPersonalDetail = new HashSet<tbl_userPersonalDetail>();
        //}

        public int userId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string emailId { get; set; }

        public DateTime dateOfBirth { get; set; }

        public string password { get; set; }

        public bool isEmailVerified { get; set; }

        public System.Guid activationCode { get; set; }

        public string resetPasswordCode { get; set; }

        public virtual ICollection<tbl_userPersonalDetail> tbl_userPersonalDetail { get; set; }

    }

}
